print('My name is Erin')
print('I was born in July')
print ('My name is Emma')
print ('I was born in February')
print ('This is confusing')
print('My favorite food is pasta')
print('My sign is cancer')
